<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE "PRODUCTS"
   (	"PRODUCT_NO" VARCHAR2(20),
	"PRODUCT_NAME" VARCHAR2(40) NOT NULL ENABLE,
	"PRODUCT_TYPE" NUMBER(3,0),
	"PROFIT_PERCENT" NUMBER(5,2) NOT NULL ENABLE,
	"UNIT_MEASURE" NUMBER,
	"SELL_PRICE" NUMBER(12,2) NOT NULL ENABLE,
	"COST_PRICE" NUMBER(12,2) NOT NULL ENABLE,
	"QTY_ON_HAND" NUMBER(6,0) DEFAULT 0,
	"STATUS" VARCHAR2(20),
	 CONSTRAINT "UQ_PRODUCTS_NAME" UNIQUE ("PRODUCT_NAME")
  USING INDEX  ENABLE,
	 CONSTRAINT "PK_PRODUCTS" PRIMARY KEY ("PRODUCT_NO")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_PRODUCTS_COST_PRICE_NONNEG" CHECK (cost_price >= 0) ENABLE,
	 CONSTRAINT "CK_PRODUCTS_SELL_PRICE_NONNEG" CHECK (sell_price >= 0) ENABLE,
	 CONSTRAINT "FK_PRODUCTS_TYPE" FOREIGN KEY ("PRODUCT_TYPE")
	  REFERENCES "PRODUCT_TYPE" ("PRODUCTTYPE_ID") ENABLE,
	 CONSTRAINT "PRODUCTS_FK1" FOREIGN KEY ("UNIT_MEASURE")
	  REFERENCES "PRODUCT_MEASURE" ("MEASURE_ID") ENABLE
   )
SQL
        );
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE "PRODUCTS" CASCADE CONSTRAINTS PURGE');
    }
};
