<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE "JOBS"
   (	"JOB_ID" NUMBER(3,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 152 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE,
	"JOB_TITLE" VARCHAR2(50) NOT NULL ENABLE,
	"MIN_SALARY" NUMBER(8,0),
	"MAX_SALARY" NUMBER(8,0),
	 CONSTRAINT "UQ_JOBS_TITLE" UNIQUE ("JOB_TITLE")
  USING INDEX  ENABLE,
	 CONSTRAINT "PK_JOBS" PRIMARY KEY ("JOB_ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "CK_JOBS_MAX_GE_MIN" CHECK (max_salary IS NULL OR min_salary IS NULL OR max_salary >= min_salary) ENABLE
   )
SQL
        );
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE "JOBS" CASCADE CONSTRAINTS PURGE');
    }
};
