<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE "SUPPLIERS"
   (	"SUPPLIER_ID" NUMBER(3,0) GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE,
	"SUPPLIER_NAME" VARCHAR2(50),
	"ADDRESS" VARCHAR2(150),
	"COUNTRY_CITY" VARCHAR2(50),
	"PHONE" VARCHAR2(15),
	"EMAIL" VARCHAR2(30),
	 CONSTRAINT "SUPPLIERS_PK" PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX  ENABLE
   )
SQL
        );
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE "SUPPLIERS" CASCADE CONSTRAINTS PURGE');
    }
};
