<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE "PRODUCT_MEASURE"
   (	"MEASURE_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE,
	"MEASURE_NAME" VARCHAR2(20),
	 CONSTRAINT "PRODUCT_MEASURE_PK" PRIMARY KEY ("MEASURE_ID")
  USING INDEX  ENABLE
   )
SQL
        );
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE "PRODUCT_MEASURE" CASCADE CONSTRAINTS PURGE');
    }
};
