<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE "FORM_CONTOL"
   (	"FORM_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 87 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE,
	"FORM_NAME" VARCHAR2(20),
	"FORM_TITLE" VARCHAR2(20),
	"CREATE_DATE" DATE DEFAULT sysdate,
	"FORM_STATUS" VARCHAR2(20),
	 CONSTRAINT "FORM_CONTOL_PK" PRIMARY KEY ("FORM_ID")
  USING INDEX  ENABLE
   )
SQL
        );
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE "FORM_CONTOL" CASCADE CONSTRAINTS PURGE');
    }
};
