<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE OR REPLACE VIEW "TOTALSALEDETAIL" ("INVOICE_NO", "INVOICE_DATE", "INVOICE_STATUS", "EMPLOYEE_NAME", "CLIENT_NO", "CLIENT_NAME", "PRODUCT_NAME", "QTY", "PRICE", "TOTAL LINE", "DISCOUNT", "DISCOUNT AMOUNT", "BALANCE") AS
  SELECT IV.INVOICE_NO, IV.INVOICE_DATE,IV.INVOICE_STATUS, E.EMPLOYEE_NAME, IV.CLIENT_NO, C.CLIENT_NAME,
P.PRODUCT_NAME, IVD.QTY, IVD.PRICE, IVD.QTY*IVD.PRICE AS "TOTAL LINE",
C.DISCOUNT, (IVD.QTY*IVD.PRICE)*C.DISCOUNT AS "DISCOUNT AMOUNT",
(IVD.QTY*IVD.PRICE)-(IVD.QTY*IVD.PRICE)*C.DISCOUNT AS "BALANCE"
FROM CLIENTS C INNER JOIN INVOICES IV ON C.CLIENT_NO = IV.CLIENT_NO
INNER JOIN EMPLOYEES E ON E.EMPLOYEE_ID = IV.EMPLOYEE_ID
INNER JOIN INVOICE_DETAILS IVD ON IV.INVOICE_NO = IVD.INVOICE_NO
INNER JOIN PRODUCTS P ON P.PRODUCT_NO = IVD.PRODUCT_NO
SQL
        );
    }

    public function down(): void
    {
        DB::unprepared('DROP VIEW "TOTALSALEDETAIL"');
    }
};
