<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        DB::unprepared(<<<'SQL'
CREATE TABLE "GROUP_USER"
   (	"G_ID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 42 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE,
	"GRUOP_NAME" VARCHAR2(20),
	"GROUP_STATUS" VARCHAR2(20),
	"CREATE_DATE" DATE DEFAULT sysdate,
	 CONSTRAINT "GROUP_USER_PK" PRIMARY KEY ("G_ID")
  USING INDEX  ENABLE
   )
SQL
        );
    }

    public function down(): void
    {
        DB::unprepared('DROP TABLE "GROUP_USER" CASCADE CONSTRAINTS PURGE');
    }
};
