<?php

namespace App\Http\Controllers;

use App\Support\CjDropshippingService;
use Illuminate\Database\QueryException;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\View\View;

class ChinaStoreController extends Controller
{
    public function index(): View
    {
        return view('china-store.index');
    }

    public function products(Request $request, CjDropshippingService $cjDropshipping): JsonResponse
    {
        $q = trim((string) $request->query('q', ''));
        $defaultPageSize = (int) Config::get('services.cj_dropshipping.page_size', 24);
        $page = (int) $request->query('page', 1);
        $perPage = (int) $request->query('per_page', $defaultPageSize);
        $page = max(1, $page);
        $perPage = max(20, min($perPage, 50));

        $data = $cjDropshipping->fetchProducts($q, $page, $perPage);

        return response()->json($data);
    }

    public function image(Request $request, CjDropshippingService $cjDropshipping): Response
    {
        $opaqueImageKey = trim((string) $request->query('url', ''));
        if ($opaqueImageKey === '') {
            return $this->placeholderImageResponse();
        }

        $imageUrl = $cjDropshipping->resolveImageKey($opaqueImageKey);
        if ($imageUrl === null) {
            return response('Invalid image key.', 400, [
                'Content-Type' => 'text/plain; charset=UTF-8',
            ]);
        }

        if (! $cjDropshipping->isAllowedImageUrl($imageUrl)) {
            return response('Forbidden image domain.', 403, [
                'Content-Type' => 'text/plain; charset=UTF-8',
            ]);
        }

        $cached = $this->readProxyCachedImage($imageUrl);
        if ($cached !== null) {
            return $this->buildImageResponse($request, $cached['binary'], $cached['content_type'], 86400);
        }

        $timeout = max(2, (int) Config::get('services.cj_dropshipping.timeout', 15));
        $maxImageBytes = max(65536, (int) Config::get('services.cj_dropshipping.max_image_bytes', 4 * 1024 * 1024));

        try {
            $response = Http::timeout($timeout)
                ->connectTimeout(min(5, $timeout))
                ->accept('image/*')
                ->withHeaders([
                    'User-Agent' => 'POS-ChinaStore-ImageProxy/1.0',
                ])
                ->get($imageUrl);
        } catch (\Throwable $e) {
            Log::warning('China Store image proxy request failed.', [
                'message' => $e->getMessage(),
            ]);

            return $this->placeholderImageResponse();
        }

        if (! $response->ok()) {
            return $this->placeholderImageResponse();
        }

        $binary = $response->body();
        if (! is_string($binary) || $binary === '') {
            return $this->placeholderImageResponse();
        }

        if (strlen($binary) > $maxImageBytes) {
            return $this->placeholderImageResponse();
        }

        $contentType = $this->normalizeImageContentType((string) $response->header('Content-Type', ''));
        if ($contentType === null) {
            $detected = @getimagesizefromstring($binary);
            $contentType = $this->normalizeImageContentType((string) ($detected['mime'] ?? ''));
        }

        if ($contentType === null) {
            return $this->placeholderImageResponse();
        }

        $this->storeProxyCachedImage($imageUrl, $binary, $contentType);

        return $this->buildImageResponse($request, $binary, $contentType, 86400);
    }

    public function import(Request $request, CjDropshippingService $cjDropshipping): JsonResponse
    {
        $validated = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            // image contains opaque source key generated by China Store product API.
            'image' => ['required', 'string', 'max:4000'],
            'cost_price' => ['required', 'numeric', 'min:0'],
        ]);

        $originalName = trim((string) $validated['name']);
        $productName = mb_substr($originalName, 0, 40);
        $sourceKey = trim((string) $validated['image']);
        $costPrice = round((float) $validated['cost_price'], 2);
        $sellPrice = round($costPrice * 1.5, 2);
        $profitPercent = 50.00;

        if ($productName === '') {
            return response()->json([
                'status' => 'error',
                'message' => 'Product name is required.',
            ], 422);
        }

        if ($this->productNameExists($productName)) {
            return response()->json([
                'status' => 'skipped',
                'message' => 'Product already exists. Import skipped.',
                'product_name' => $productName,
            ]);
        }

        $sourceImageUrl = $cjDropshipping->resolveImageKey($sourceKey);
        if ($sourceImageUrl === null || ! $cjDropshipping->isAllowedImageUrl($sourceImageUrl)) {
            return response()->json([
                'status' => 'error',
                'message' => 'Invalid product image source.',
            ], 422);
        }

        $storedImagePath = $this->downloadAndStoreImage($sourceImageUrl);
        if ($storedImagePath === null) {
            return response()->json([
                'status' => 'error',
                'message' => 'Failed to download product image.',
            ], 422);
        }

        try {
            $productNo = DB::connection('oracle')->transaction(function () use (
                $productName,
                $storedImagePath,
                $costPrice,
                $sellPrice,
                $profitPercent
            ): string {
                $productNo = $this->nextProductCode();

                DB::connection('oracle')->insert(
                    'INSERT INTO PRODUCTS (PRODUCT_NO, PRODUCT_NAME, PRODUCT_TYPE, SELL_PRICE, COST_PRICE, PROFIT_PERCENT, UNIT_MEASURE, QTY_ON_HAND, STATUS)
                     VALUES (:product_no, :product_name, :product_type, :sell_price, :cost_price, :profit_percent, :unit_measure, :qty_on_hand, :status)',
                    [
                        'product_no' => $productNo,
                        'product_name' => $productName,
                        'product_type' => null,
                        'sell_price' => $sellPrice,
                        'cost_price' => $costPrice,
                        'profit_percent' => $profitPercent,
                        'unit_measure' => null,
                        'qty_on_hand' => 0,
                        'status' => null,
                    ]
                );

                DB::connection('oracle')->statement(
                    'INSERT INTO PRODUCT_PHOTO (PRODUCT_ID, MEDIA, CREATED_AT, UPDATED_AT)
                     VALUES (:product_id, TO_BLOB(UTL_RAW.CAST_TO_RAW(:media)), SYSTIMESTAMP, SYSTIMESTAMP)',
                    [
                        'product_id' => $productNo,
                        'media' => $storedImagePath,
                    ]
                );

                return $productNo;
            }, 3);
        } catch (QueryException $e) {
            if (str_contains($e->getMessage(), 'ORA-00001') && $this->productNameExists($productName)) {
                return response()->json([
                    'status' => 'skipped',
                    'message' => 'Product already exists. Import skipped.',
                    'product_name' => $productName,
                ]);
            }

            return response()->json([
                'status' => 'error',
                'message' => 'Failed to import product.',
            ], 500);
        }

        return response()->json([
            'status' => 'success',
            'message' => 'Product imported to stock.',
            'data' => [
                'product_no' => $productNo,
                'name' => $productName,
                'cost_price' => $costPrice,
                'selling_price' => $sellPrice,
                'profit_percent' => $profitPercent,
                'stock' => 0,
            ],
        ]);
    }

    private function productNameExists(string $productName): bool
    {
        return DB::connection('oracle')
            ->table('PRODUCTS')
            ->whereRaw('UPPER(PRODUCT_NAME) = ?', [mb_strtoupper($productName)])
            ->exists();
    }

    private function nextProductCode(): string
    {
        $lastCode = DB::connection('oracle')
            ->table('PRODUCTS')
            ->selectRaw('MAX(PRODUCT_NO) as last_code')
            ->value('last_code');

        if ($lastCode === null) {
            return 'P0001';
        }

        $digits = preg_replace('/\D/', '', (string) $lastCode);
        $digits = $digits === null ? '' : $digits;

        if ($digits === '') {
            return 'P0001';
        }

        $number = (int) $digits;
        $length = max(4, strlen($digits));

        return 'P'.str_pad((string) ($number + 1), $length, '0', STR_PAD_LEFT);
    }

    private function downloadAndStoreImage(string $sourceImageUrl): ?string
    {
        $cached = $this->readProxyCachedImage($sourceImageUrl);
        if ($cached !== null) {
            $binary = $cached['binary'];
            $contentType = $cached['content_type'];
        } else {
            $timeout = max(2, (int) Config::get('services.cj_dropshipping.timeout', 15));
            $maxImageBytes = max(65536, (int) Config::get('services.cj_dropshipping.max_image_bytes', 4 * 1024 * 1024));

            try {
                $response = Http::timeout($timeout)
                    ->connectTimeout(min(5, $timeout))
                    ->accept('image/*')
                    ->withHeaders([
                        'User-Agent' => 'POS-ChinaStore-Import/1.0',
                    ])
                    ->get($sourceImageUrl);
            } catch (\Throwable $e) {
                Log::warning('China Store import image download failed.', [
                    'message' => $e->getMessage(),
                ]);

                return null;
            }

            if (! $response->ok()) {
                return null;
            }

            $binary = $response->body();
            if (! is_string($binary) || $binary === '' || strlen($binary) > $maxImageBytes) {
                return null;
            }

            $contentType = $this->normalizeImageContentType((string) $response->header('Content-Type', ''));
            if ($contentType === null) {
                $detected = @getimagesizefromstring($binary);
                $contentType = $this->normalizeImageContentType((string) ($detected['mime'] ?? ''));
            }

            if ($contentType === null) {
                return null;
            }

            $this->storeProxyCachedImage($sourceImageUrl, $binary, $contentType);
        }

        $extension = $this->extensionFromImageContentType($contentType);
        if ($extension === null) {
            return null;
        }

        $directory = public_path('images/products');
        if (! is_dir($directory) && ! mkdir($directory, 0775, true) && ! is_dir($directory)) {
            return null;
        }

        $filename = uniqid('china_product_', true).'.'.$extension;
        $absolutePath = $directory.DIRECTORY_SEPARATOR.$filename;

        $written = @file_put_contents($absolutePath, $binary);
        if ($written === false || $written < 1) {
            return null;
        }

        return 'images/products/'.$filename;
    }

    private function normalizeImageContentType(string $contentType): ?string
    {
        $type = strtolower(trim($contentType));
        if ($type === '') {
            return null;
        }

        $type = trim(strtok($type, ';') ?: '');

        $allowed = [
            'image/jpeg',
            'image/jpg',
            'image/png',
            'image/webp',
            'image/gif',
            'image/avif',
        ];

        if (! in_array($type, $allowed, true)) {
            return null;
        }

        return $type === 'image/jpg' ? 'image/jpeg' : $type;
    }

    private function extensionFromImageContentType(string $contentType): ?string
    {
        return match (strtolower($contentType)) {
            'image/jpeg' => 'jpg',
            'image/png' => 'png',
            'image/webp' => 'webp',
            'image/gif' => 'gif',
            'image/avif' => 'avif',
            default => null,
        };
    }

    /**
     * @return array{binary:string,content_type:string}|null
     */
    private function readProxyCachedImage(string $imageUrl): ?array
    {
        $directory = $this->proxyCacheDirectory();
        if (! is_dir($directory)) {
            return null;
        }

        $hash = sha1($imageUrl);
        $pattern = $directory.DIRECTORY_SEPARATOR.$hash.'.*';
        $files = glob($pattern);
        if (! is_array($files) || $files === []) {
            return null;
        }

        $ttlSeconds = max(60, (int) Config::get('services.cj_dropshipping.image_cache_ttl', 86400));
        $now = time();

        foreach ($files as $file) {
            if (! is_string($file) || ! is_file($file)) {
                continue;
            }

            $mtime = @filemtime($file);
            if ($mtime !== false && ($now - $mtime) > $ttlSeconds) {
                @unlink($file);
                continue;
            }

            $binary = @file_get_contents($file);
            if (! is_string($binary) || $binary === '') {
                @unlink($file);
                continue;
            }

            $detected = @getimagesizefromstring($binary);
            $contentType = $this->normalizeImageContentType((string) ($detected['mime'] ?? ''));

            if ($contentType === null) {
                @unlink($file);
                continue;
            }

            return [
                'binary' => $binary,
                'content_type' => $contentType,
            ];
        }

        return null;
    }

    private function storeProxyCachedImage(string $imageUrl, string $binary, string $contentType): void
    {
        $extension = $this->extensionFromImageContentType($contentType);
        if ($extension === null) {
            return;
        }

        $directory = $this->proxyCacheDirectory();
        if (! is_dir($directory) && ! mkdir($directory, 0775, true) && ! is_dir($directory)) {
            return;
        }

        $hash = sha1($imageUrl);
        $pattern = $directory.DIRECTORY_SEPARATOR.$hash.'.*';
        $existing = glob($pattern);
        if (is_array($existing)) {
            foreach ($existing as $file) {
                if (is_string($file) && is_file($file)) {
                    @unlink($file);
                }
            }
        }

        $absolutePath = $directory.DIRECTORY_SEPARATOR.$hash.'.'.$extension;
        @file_put_contents($absolutePath, $binary);
    }

    private function proxyCacheDirectory(): string
    {
        return public_path('images/china-store-cache');
    }

    private function buildImageResponse(Request $request, string $binary, string $contentType, int $maxAgeSeconds): Response
    {
        $etag = '"'.sha1($binary).'"';
        $ifNoneMatch = (string) $request->headers->get('If-None-Match', '');
        if ($ifNoneMatch !== '' && str_contains($ifNoneMatch, $etag)) {
            return response('', 304, [
                'ETag' => $etag,
                'Cache-Control' => 'public, max-age='.$maxAgeSeconds,
                'X-Content-Type-Options' => 'nosniff',
            ]);
        }

        return response($binary, 200, [
            'Content-Type' => $contentType,
            'Content-Length' => (string) strlen($binary),
            'ETag' => $etag,
            'Cache-Control' => 'public, max-age='.$maxAgeSeconds,
            'X-Content-Type-Options' => 'nosniff',
        ]);
    }

    private function placeholderImageResponse(): Response
    {
        $svg = <<<'SVG'
<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600">
  <rect width="600" height="600" fill="#f3f7fb"/>
  <rect x="80" y="80" width="440" height="440" rx="20" fill="#e5ebf3" stroke="#d6dfeb" stroke-width="4"/>
  <circle cx="220" cy="250" r="44" fill="#c6d3e3"/>
  <path d="M120 430 L250 300 L330 380 L420 290 L520 430 Z" fill="#c6d3e3"/>
</svg>
SVG;

        return response($svg, 200, [
            'Content-Type' => 'image/svg+xml; charset=UTF-8',
            'Cache-Control' => 'public, max-age=86400',
            'X-Content-Type-Options' => 'nosniff',
        ]);
    }
}
